Journal/Models/Journal.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.IdentityModel.Tokens;

namespace Journal.Models
{
    public class Journal
    { 
        public int Name { get; set; }
        public string Surname { get; set; }
        public int ID { get; set; }

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Title { get; set; }
        public decimal PostNumber { get; set; }
    }
}

Journal/Controllers/JournalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Journal.Data;
using Journal.Models;


namespace Journal.Controllers
{
    public class JournalController : Controller
    {
        private readonly JournalContext _context;
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<User> _userManager;


        // 3. Dependency inject the UserManager Class
        public JournalController(ILogger<HomeController> logger, JournalContext context, UserManager<User> userManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }


        // GET: Journal
        public async Task<IActionResult> Index(string searchString)
        {
            var journal = from m in _context.Journal
                          select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                journal = journal.Where(s => s.Symptoms.Contains(searchString));

            }

            return View(await journal.ToListAsync());
        }

        // GET: Journal/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journal
                .FirstOrDefaultAsync(m => m.ID == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        // GET: Journal/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Journal/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,ID,Date,Day,Symptoms, Body")] JournalModel journal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(journal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(journal);
        }

        // GET: Journal/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journal.FindAsync(id);
            if (journal == null)
            {
                return NotFound();
            }
            return View(journal);
        }

        // POST: Journal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,ID,Date,Day,Symptoms,Body")] JournalModel journal)
        {
            if (id != journal.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(journal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JournalExists(journal.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(journal);
        }

        // GET: Journal/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journal
                .FirstOrDefaultAsync(m => m.ID == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        // POST: Journal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var journal = await _context.Journal.FindAsync(id);
            _context.Journal.Remove(journal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JournalExists(int id)
        {
            return _context.Journal.Any(e => e.ID == id);
        }
    }
}


//Ruan my code werk nie hier nie dis hoekom ek dit net gecomment het 

//namespace Journal.Controllers
//{
//    public class JournalController : Controller
//    {
//        private readonly ILogger<HomeController> _logger;
//        private readonly JournalContext _context;
//        private readonly UserManager<User> _userManager;

//        // 3. Dependency inject the UserManager Class
//        public JournalController(ILogger<HomeController> logger, JournalContext context, UserManager<User> userManager)
//        {
//            _logger = logger;
//            _context = context;
//            _userManager = userManager;
//        }

//        // GET: Todoes
//        public async Task<IActionResult> Index()
//        {
//            // Test to see if the user is logged in
//            if (User.Identity.IsAuthenticated)
//            {
//                // Get the id of the current loggedin user
//                string id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
//                User currentUser = await _context.User
//                    .Include(u => u.JournalModel)
//                    .Include(u => u.UserJournalModel)
//                        .ThenInclude(ut => ut.Journal)
//                    .FirstOrDefaultAsync(u => u.Id == id);

//                if (currentUser == null)
//                {
//                    return NotFound();
//                }


//                return View(currentUser);
//            }
//            //await _context.Journal.ToListAsync()
//            return View();
//        }

//        // GET: Todoes/Details/5
//        public async Task<IActionResult> Details(int? id)
//        {
//            if (id == null)
//            {
//                return NotFound();
//            }

//            var journal = await _context.Journal
//                .Include(t => t.UserJournal)
//                    .ThenInclude(t => t.User)
//                .FirstOrDefaultAsync(m => m.ID == id);
//            if (journal == null)
//            {
//                return NotFound();
//            }

//            return View(journal);
//        }

//        // GET: Todoes/Create
//        public IActionResult Create()
//        {
//            List<User> allUsers = _context.Users.ToList();
//            var selectAllUsers = allUsers.Select(x => new SelectListItem() { Text = x.FirstName, Value = x.Id, Selected = true });
//            // ViewBag.Name = "Cool Title";
//            ViewData["users"] = new MultiSelectList(selectAllUsers, "Value", "Text");
//            //var todo = new TodoViewModel();
//            //todo.UserIds = new List<string>();
//            return View();
//        }

//        // POST: Todoes/Create
//        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
//        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> Create([Bind("Id,Title,Body,UserIds")] JournalModel journalModel) //Change todo to todoModel to make more sense
//        {
//            // Make sure that the todo is related to the user on create
//            if (ModelState.IsValid)
//            {
//                var todo = new JournalModel
//                {
//                    Day = journalModel.Day,
//                    Body = journalModel.Body,
//                    Owner = _userManager.GetUserAsync(User).Result
//                };
//                journalModel.UserJournal = new List<UserJournal>();

//                if (journalModel.UserIds != null)
//                {
//                    List<User> allUsers = _context.User.Where(user => journalModel.UserIds.Contains(user.Id)).ToList();

//                    foreach (User user in allUsers)
//                    {
//                        _logger.LogInformation(user.LastName);
//                        todo.UserJournal.Add(new UserJournal { Journal = journalModel, User = user });
//                    }
//                    _context.Journal.Add(todo);
//                    await _context.SaveChangesAsync();
//                    return RedirectToAction(nameof(Index));
//                }
//                else
//                {
//                    _context.Journal.Add(todo);
//                    await _context.SaveChangesAsync();
//                    return RedirectToAction(nameof(Index));
//                }

//            }
//            return View(journalModel);
//        }

//        // GET: Todoes/Edit/5
//        public async Task<IActionResult> Edit(int? id)
//        {
//            if (id == null)
//            {

Journal/Views/Journal/Create.cshtml
@model Journal.Models.JournalModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Journal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Symptoms" class="control-label"></label>
                <input asp-for="Symptoms" class="form-control" />
                <span asp-validation-for="Symptoms" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Journal/Views/Journal/Delete.cshtml
@model Journal.Models.JournalModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Journal</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Symptoms)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Symptoms)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>

    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Journal/Views/Journal/Details.cshtml
@model Journal.Models.JournalModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Journal</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Symptoms)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Symptoms)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Journal/Views/Journal/Edit.cshtml
@model Journal.Models.JournalModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Journal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Symptoms" class="control-label"></label>
                <input asp-for="Symptoms" class="form-control" />
                <span asp-validation-for="Symptoms" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Journal/Views/Journal/Index.cshtml
@model IEnumerable<Journal.Models.JournalModel>

@{
    ViewData["Title"] = "Index";
}

<h3>This is where you will create your daily Journal entry.</h3>
<br />

    <button>
        <a asp-action="Create">Create New</a>
    </button>
   <br/>
   <br />
   <br />

<form asp-controller="Journal" asp-action="Index">
    <p>
        <div class="search">

            <h4>Symptoms: <input type="text" name="SearchString">
            <input type="submit" value="Filter"</h4>
        </div>
       
    </p>
</form>

<br/>
<br/>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Day)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Symptoms)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Day)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Symptoms)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>



            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Journal/Views/Journal/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>
<p>This is where you can add a journal entry</p>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
  
</ul>